### ISSUE TITLE
DIAG-C400-lin-LimBio

### ISSUE THREAD

**Issue by HauHe** [KTH-dESA/OSeMBE_ECEMF#42]
The ban of imported Biomass in the EU increases the BM consumption in CH and UK.

- [ ] Limit imports of BM in CH, UK, NO. Total ban? Or perhaps to same amount as the domestic production?

**Comment by willu47** [comment]
Total ban agreed

**Comment by EmiFej** [comment]
- The DIAG-C400-lin-LimBio scenario had 0 as TotalAnnualMaxCapacityInvestment for the new BM technologies from 2015-2025 (11 years). After that there were no inputs for any of the BM technologies. CH, UK, NO, together with the EU MS are now unable to invest in new BM technologies for the whole modelling period (2015-2060). 

- Existing residual capacity for BM technologies amount to 0 by 2045 and onwards, meaning the model should not use any BM in the 2045-2060 period in this scenario. 

- TotalAnnualMaxCapacity for all BM importing technologies set to 0 for the 2015-2060 period.

**Comment by willu47** [comment]
Suggest replacing `TotalAnnualMaxCapacityInvestment` with `TotalTechnologyAnnualActivityUpperLimit` for biomass imports

**Comment by EmiFej** [comment]
Removed the `TotalAnnualMaxCapacity` for BM importing technologies previously implemented. Instead, added a `TotalTechnologyAnnualActivityUpperLimit` for biomass imports. 

Removed the `TotalAnnualMaxCapacityInvestment` for CCS technologies from 2026-2060, reverted back the previous changes made, so to not double constrain it with the `TotalAnnualMaxCapacityInvestment` and `TotalTechnologyAnnualActivityUpperLimit`
