### ISSUE TITLE
The documentation needs to be updated

### ISSUE THREAD

**Issue by Timon-R** [KTH-dESA/OSeMBE_ECEMF#67]
First, there is an error in the [OSEMBE documentation](https://osembe.readthedocs.io/en/latest/naming.html).
The naming convention of technologies is described as AABBCCDDEF (10 digits). It should only be one D (9 digits in total).

Second, the emission codes are unclear. I found the following ones for the example of Finland (scenario WP1_NetZero):

- FIHO (water vapor?)
- FIPM25 (this is particular matter 2.5)
- FISO (sulfur dioxide?)
- FIWI (?)
- FIWO (Dummy?)

**Comment by HauHe** [comment]
Dear @Timon-R,
thanks for this creating this issue. Since the documentation is hosted under the OSeMBE (not ECEMF specific) repo here: https://github.com/kTH-dESA/oSeMBE could you please re-create the issue there?

**Comment by Timon-R** [comment]
Alright, done so
