### ISSUE TITLE
A python script for decoding OSEMBE codes for better understanding

### ISSUE THREAD

**Issue by Timon-R** [KTH-dESA/OSeMBE_ECEMF#68]
I wrote a python script that can be used to decipher OSEMBE codes of technologies and fuels.
You can access it here: [Code Decipherer](https://github.com/Timon-R/Code_Decipherer)

**Comment by HauHe** [comment]
Hi @Timon-R,
that sounds pretty cool!
Thanks for looking into this. Since this is the ECEMF project specific repo of OSeMBE, but your script seems OSeMBE generic, would you mind recreating the issue on the general OSeMBE repo here: https://github.com/kTH-dESA/oSeMBE ?
