### ISSUE TITLE
Add workflow to this repository

### ISSUE THREAD

**Issue by willu47** [KTH-dESA/OSeMBE_ECEMF#8]
I would suggest adding the snakemake workflow to this repository.

While you might prefer to keep the workflow and data separate, I think at the moment that it would be easier to manage if they were both in the same repository.

**Comment by HauHe** [comment]
I see your point. 
Should I then remove it from the demos repo? Or just leave it as it is?

**Comment by willu47** [comment]
You can leave it in the demos repo, perhaps with a note and link to this repo?

**Comment by HauHe** [comment]
Ok, then I leave it ther as it is and also don't do the effort of copying the version history. Since it is a sub-folder of demos it seems anyway somewhat tricky from what I read.

**Comment by HauHe** [comment]
This issue has been addressed. On the main branch the workflow from datapackage to results folder with csvs is added. On the iamc_results branch there is a workflow that creats for each rule an own environment and includes the conversion of the results csvs to an excel file in iamc format. It works on Mac, but not on the workstations.
